name: download

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8888
      - TORRENTING_PORT=28888
    ports:
      - 28888:28888
      - 28888:28888/udp
      - 8888:8888
    volumes:
      - ${DOCKER_DATA}/qbittorrent/config:/config
      - ${QBITTORRENT_DATA}:/downloads
    restart: always

  aria2:
    image: 'johngong/aria2:latest'
    container_name: aria2
    volumes:
      - ${DOCKER_DATA}/aria2/config:/config
      - ${RESOURCE_DATA}/aria2:/Downloads
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
      - ARIA2_RPC_LISTEN_PORT=6800
      - ARIA2_LISTEN_PORT=6882
    ports:
      - 6800:6800
      - 6880:8080
      - 6882:6882
      - 6882:6882/udp
    restart: always
