name: media

services:
  openlist:
    image: 'openlistteam/openlist:latest'
    container_name: openlist
    environment:
      - TZ=${TZ}
      - UMASK=022
    user: '${PUID}:${PGID}'
    volumes:
      - ${DOCKER_DATA}/openlist:/opt/openlist/data
      - ${RESOURCE_DATA}:/resource
      - ${QBITTORRENT_DATA}:/qbit
    restart: always
    ports:
      - 5244:5244

  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA}/komga/config:/config
      - ${DOCKER_DATA}/komga/data:/data
      - ${DOCKER_DATA}/komga/tmp:/tmp
      - ${RESOURCE_DATA}:/resource

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: '${PUID}:${PGID}'
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA}/jellyfin/config:/config
      - ${DOCKER_DATA}/jellyfin/cache:/cache
      - ${DOCKER_DATA}/jellyfin/media:/media
      - ${RESOURCE_DATA}:/resource
    ports:
      - 8096:8096
      - 7359:7359/udp
    restart: always

  volix:
    image: djwl/volix:latest
    container_name: volix
    restart: always
    environment:
      - TZ=${TZ}
    ports:
      - '3000:3000'
    volumes:
      - ${DOCKER_DATA}/volix:/app/data
